apiVersion: apps/v1
kind: Deployment
metadata:
  name: uad-nonprod-deployment
  labels:
    app: uad
    environment: nonprod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uad
      environment: nonprod
  template:
    metadata:
      labels:
        app: uad
        environment: nonprod
    spec:
      containers:
      - name: uad-container
        image: uad:v1
        ports:
        - containerPort: 80
